CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	email VARCHAR(100) UNIQUE,
	password VARCHAR(128) NOT NULL,
	salt VARCHAR(128) NOT NULL
)

CREATE TABLE rooms (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) DEFAULT NULL,
	user_white INTEGER NOT NULL REFERENCES USERS(id),
	user_black INTEGER DEFAULT NULL REFERENCES USERS(id),
	ini_date VARCHAR(255) NOT NULL,
	fi_date VARCHAR(255) DEFAULT NULL,
	fen VARCHAR(255) NOT NULL DEFAULT 'start'
)
CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
	"sess" json NOT NULL,
	"expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;